name: flutter_application_w8
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animations: ^2.0.7
  animated_text_kit: ^4.2.2
  flutter_sequence_animation: ^4.0.0
  rubber: ^1.1.0
  firebase_core: ^2.15.1
  firebase_auth: ^4.8.0
  flutter_progress_hud: ^2.0.2
  cloud_firestore: ^4.9.1
  intl: ^0.18.1
  image_picker: ^1.0.4
  firebase_storage: ^11.2.6
  flutter_cache_manager: ^3.3.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - images/message.png